<a href="https://colab.research.google.com/github/sonky20/sonky/blob/master/2%EC%9D%BC%EC%B0%A8_%ED%85%90%EC%84%9C%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd

scalar = torch.tensor(5)
print(scalar)
print(scalar.shape)

tensor(5)
torch.Size([])


In [3]:
vector = torch.tensor([1,2,3,4])
print(vector)
print(vector.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [5]:
matrix = torch.tensor([[1,2,3], [4,5,6]])
print(matrix)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [6]:
tensor3d = torch.rand(2,3,4)
print(tensor3d)
print(tensor3d.shape)

tensor([[[0.6448, 0.8375, 0.8562, 0.6440],
         [0.8216, 0.9203, 0.9197, 0.9778],
         [0.8088, 0.7120, 0.4916, 0.3123]],

        [[0.4951, 0.7784, 0.4236, 0.8433],
         [0.0789, 0.2375, 0.6751, 0.0147],
         [0.5046, 0.6670, 0.5768, 0.9397]]])
torch.Size([2, 3, 4])


In [7]:
int_tensor = torch.tensor([1,2,3,4], dtype=torch.int64)
print(int_tensor)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(float_tensor)

tensor([1, 2, 3, 4])
tensor([1., 2., 3.])
