<a href="https://colab.research.google.com/github/sonky20/sonky/blob/master/2%EC%9D%BC%EC%B0%A8_%ED%85%90%EC%84%9C%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd

scalar = torch.tensor(5)
print(scalar)
print(scalar.shape)

tensor(5)
torch.Size([])


In [2]:
vector = torch.tensor([1,2,3,4])
print(vector)
print(vector.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [3]:
matrix = torch.tensor([[1,2,3], [4,5,6]])
print(matrix)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [4]:
tensor3d = torch.rand(2,3,4)
print(tensor3d)
print(tensor3d.shape)

tensor([[[0.0193, 0.9669, 0.2034, 0.7815],
         [0.6907, 0.3751, 0.3216, 0.9402],
         [0.9637, 0.1443, 0.6038, 0.7445]],

        [[0.6302, 0.0419, 0.9939, 0.9427],
         [0.5595, 0.1512, 0.4289, 0.5554],
         [0.1873, 0.4330, 0.8285, 0.2496]]])
torch.Size([2, 3, 4])


In [5]:
int_tensor = torch.tensor([1,2,3,4], dtype=torch.int64)
print(int_tensor)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(float_tensor)

tensor([1, 2, 3, 4])
tensor([1., 2., 3.])
